// See README.md for license details.

package hjxl

import chisel3._
import chisel3.simulator.scalatest.ChiselSim
import org.scalatest.freespec.AnyFreeSpec
import org.scalatest.matchers.must.Matchers

class DcTokenTraceStageSpec extends AnyFreeSpec with Matchers with ChiselSim {
  private case class PreparedDc(current: Int, west: Int, north: Int, northwest: Int)

  "DcTokenTraceStage matches libjxl-tiny fixed DC-token oracle for prepared constant-frame DC planes" in {
    // Generated by:
    // python3 tools/hjxl_reference.py --width 9 --height 1 --pattern constant \
    //   --fixed-dct-only-dc-tokens-npy build-codex/oracle/constant-9x1-fixed-dc.npy
    val expected = Seq(
      (26, 704),
      (13, 0),
      (26, 45),
      (33, 0),
      (26, 38),
      (21, 0)
    )

    val yDc = 352
    val xDc = -23
    val bDc = 19
    val prepared = Seq(yDc, yDc, xDc, xDc, bDc, bDc).grouped(2).flatMap {
      case Seq(first, second) =>
        Seq(
          PreparedDc(current = first, west = 0, north = 0, northwest = 0),
          PreparedDc(current = second, west = first, north = first, northwest = first)
        )
    }.toSeq

    simulate(new DcTokenTraceStage()) { dut =>
      dut.io.trace.ready.poke(true.B)
      for (((sample, (context, value)), ordinal) <- prepared.zip(expected).zipWithIndex) {
        dut.io.input.valid.poke(true.B)
        dut.io.input.bits.group.poke(ordinal.U)
        dut.io.input.bits.current.poke(sample.current.S)
        dut.io.input.bits.west.poke(sample.west.S)
        dut.io.input.bits.north.poke(sample.north.S)
        dut.io.input.bits.northwest.poke(sample.northwest.S)
        dut.io.input.ready.expect(true.B)
        withClue(s"DC token $ordinal context=$context value=$value") {
          dut.io.trace.valid.expect(true.B)
          dut.io.trace.bits.stage.expect(TraceStage.DcTokens.U)
          dut.io.trace.bits.group.expect(ordinal.U)
          dut.io.trace.bits.index.expect(context.U)
          dut.io.trace.bits.value.expect(value.S)
        }
        dut.clock.step()
      }
      dut.io.input.valid.poke(false.B)
      dut.io.trace.valid.expect(false.B)
    }
  }
}
