// See README.md for license details.

package hjxl

import chisel3._
import chisel3.simulator.scalatest.ChiselSim
import org.scalatest.freespec.AnyFreeSpec
import org.scalatest.matchers.must.Matchers

class FrameDctOnlyAcMetadataTokenTraceStageSpec extends AnyFreeSpec with Matchers with ChiselSim {
  private val config = HjxlConfig(maxFrameWidth = 16, maxFrameHeight = 8)

  private def pokeConfig(
      dut: FrameDctOnlyAcMetadataTokenTraceStage,
      width: Int,
      height: Int,
      fixedRawQuant: Int = 0
  ): Unit = {
    dut.io.config.xsize.poke(width.U)
    dut.io.config.ysize.poke(height.U)
    dut.io.config.distanceQ8.poke(256.U)
    dut.io.config.fixedPointScale.poke(QuantizeDct8x8Block.DefaultScaleQ16.U)
    dut.io.config.fixedInvQacQ16.poke(QuantizeDct8x8Block.DefaultInvQacQ16.U)
    dut.io.config.fixedRawQuant.poke(fixedRawQuant.U)
    dut.io.config.enableXyb.poke(false.B)
    dut.io.config.enableDct.poke(false.B)
    dut.io.config.enableQuant.poke(true.B)
    dut.io.config.enableTokenize.poke(true.B)
    dut.io.config.tokenSelect.poke(TokenTraceSelect.AcMetadata.U)
  }

  private def drivePixel(dut: FrameDctOnlyAcMetadataTokenTraceStage, x: Int, y: Int): Unit = {
    dut.io.input.valid.poke(true.B)
    dut.io.input.bits.x.poke(x.U)
    dut.io.input.bits.y.poke(y.U)
    dut.io.input.bits.r.poke((x * 17 + y).S)
    dut.io.input.bits.g.poke((x * 3 + y * 5).S)
    dut.io.input.bits.b.poke((x + y * 11).S)
    dut.io.input.ready.expect(true.B)
    dut.clock.step()
  }

  "FrameDctOnlyAcMetadataTokenTraceStage emits fixed-path AC metadata tokens" in {
    simulate(new FrameDctOnlyAcMetadataTokenTraceStage(config)) { dut =>
      val width = 9
      val height = 1
      pokeConfig(dut, width, height)
      dut.io.input.valid.poke(false.B)
      dut.io.trace.ready.poke(false.B)
      dut.clock.step()

      for (x <- 0 until width) {
        drivePixel(dut, x, y = 0)
      }
      dut.io.input.valid.poke(false.B)

      // Generated by:
      // python3 tools/hjxl_reference.py --width 9 --height 1 --pattern constant \
      //   --fixed-dct-only-ac-metadata-tokens-npy build-codex/oracle/constant-9x1-fixed-acmeta.npy
      val expected = Seq(
        (2, 0),
        (1, 0),
        (10, 0),
        (10, 0),
        (6, 8),
        (5, 0),
        (0, 8),
        (0, 8)
      )

      dut.io.trace.ready.poke(true.B)
      for (((context, value), ordinal) <- expected.zipWithIndex) {
        withClue(s"token $ordinal context=$context value=$value") {
          dut.io.trace.valid.expect(true.B)
          dut.io.trace.bits.stage.expect(TraceStage.AcMetadataTokens.U)
          dut.io.trace.bits.group.expect(ordinal.U)
          dut.io.trace.bits.index.expect(context.U)
          dut.io.trace.bits.value.expect(value.S)
          dut.io.traceLast.expect((ordinal == expected.length - 1).B)
        }
        dut.clock.step()
      }

      dut.io.trace.valid.expect(false.B)
      dut.io.input.ready.expect(true.B)
      dut.io.overflow.expect(false.B)
    }
  }

  "FrameDctOnlyAcMetadataTokenTraceStage uses fixed raw quant overrides in quant-field tokens" in {
    simulate(new FrameDctOnlyAcMetadataTokenTraceStage(config)) { dut =>
      val width = 8
      val height = 1
      val rawQuant = 7
      pokeConfig(dut, width, height, fixedRawQuant = rawQuant)
      dut.io.input.valid.poke(false.B)
      dut.io.trace.ready.poke(false.B)
      dut.clock.step()

      for (x <- 0 until width) {
        drivePixel(dut, x, y = 0)
      }
      dut.io.input.valid.poke(false.B)
      dut.io.trace.ready.poke(true.B)

      for (ordinal <- 0 until 3) {
        withClue(s"metadata pre-quant token $ordinal") {
          dut.io.trace.valid.expect(true.B)
        }
        dut.clock.step()
      }

      dut.io.trace.valid.expect(true.B)
      dut.io.trace.bits.stage.expect(TraceStage.AcMetadataTokens.U)
      dut.io.trace.bits.group.expect(3.U)
      dut.io.trace.bits.index.expect(6.U)
      dut.io.trace.bits.value.expect(12.S)
      dut.io.traceLast.expect(false.B)
      dut.clock.step()

      dut.io.trace.valid.expect(true.B)
      dut.io.trace.bits.stage.expect(TraceStage.AcMetadataTokens.U)
      dut.io.trace.bits.group.expect(4.U)
      dut.io.trace.bits.index.expect(0.U)
      dut.io.trace.bits.value.expect(8.S)
      dut.io.traceLast.expect(true.B)
      dut.clock.step()

      dut.io.overflow.expect(false.B)
    }
  }
}
