// Generated by tools/hjxl_generate_abi.py. Do not edit by hand.

package hjxl

object HjxlAbiGenerated {
  val SchemaVersion = 1

  object AxiLite {
    val AddrBits = 8
    val DataBits = 32
    val StrbBits = 4

    object Register {
      val StatusControl = 0
      val Xsize = 4
      val Ysize = 8
      val DistanceQ8 = 12
      val FixedPointScale = 16
      val FixedInvQacQ16 = 20
      val FixedRawQuant = 24
      val Flags = 28
      val FixedYtox = 32
      val FixedYtob = 36
      val Identity = 40
      val AbiVersion = 44
      val Capabilities = 48
      val MaxFrameGeometry = 52
      val ActiveRoute = 56
      val BuildId = 60
    }

    object RegisterAccess {
      val StatusControl = "rw1c"
      val Xsize = "rw"
      val Ysize = "rw"
      val DistanceQ8 = "rw"
      val FixedPointScale = "rw"
      val FixedInvQacQ16 = "rw"
      val FixedRawQuant = "rw"
      val Flags = "rw"
      val FixedYtox = "rw"
      val FixedYtob = "rw"
      val Identity = "ro"
      val AbiVersion = "ro"
      val Capabilities = "ro"
      val MaxFrameGeometry = "ro"
      val ActiveRoute = "ro"
      val BuildId = "ro"
    }

    object StatusBit {
      val ProtocolError = 0
      val Busy = 1
      val Overflow = 2
      val UnsupportedDistance = 3
    }

    object ControlBit {
      val ClearProtocolError = 0
    }
  }

  object Trace {
    val StageBits = 8
    val StageShift = 0
    val GroupBits = 16
    val GroupShift = 8
    val IndexBits = 32
    val IndexShift = 24
    val ValueBits = 32
    val ValueShift = 56
    val PackedBits = 88
    val PackedBytes = 11
    val Kv260CaptureWordBytes = 16

    object Stage {
      val InputPadded = 0
      val Xyb = 1
      val RawDct8x8 = 2
      val RawQuantField = 3
      val YtoxMap = 4
      val YtobMap = 5
      val AcStrategy = 6
      val QuantDc = 7
      val QuantizedAc = 8
      val NumNonzeros = 9
      val DcTokens = 10
      val AcMetadataTokens = 11
      val AcTokens = 12
      val AqContrast = 13
      val AqFuzzyErosion = 14
      val AqStrategyMask = 15
      val AqNonlinearMask = 16
      val AqHfModulation = 17
    }
  }

  object TokenSelect {
    val Dc = 0
    val AcMetadata = 1
    val AcTokens = 2
    val AqContrast = 3
  }

  object Discovery {
    val Identity = 1212831820L
    val AbiMajor = 1
    val AbiMinor = 5
    val AbiVersion = 65541L
    val BuildId = 539363090L

    object CapabilityBit {
      val RgbInput = 0
      val PreparedDctInput = 1
      val EstimatedCfl = 2
      val AxiLite = 3
      val AxiStream = 4
      val TraceOutput = 5
      val HostBitstreamAssemblyRequired = 6
      val FrameConfigSnapshot = 7
      val FullWordInputKeep = 8
      val CallerCfl = 9
    }

    object CapabilityProfile {
      val Rgb = 249L
      val PreparedDirect = 1018L
      val PreparedEstimatedCfl = 510L
    }

    object Route {
      val PreparedDirect = 128
      val PreparedEstimatedCfl = 129
      val Unavailable = 255
    }
  }

  object PreparedDctStream {
    val WordBits = 32
    val ScalarWords = 9
    val Channels = 3
    val CoefficientsPerChannel = 64
    val CoefficientWords = 192
    val WordsPerBlock = 201
    val CoefficientBase = 9
    val Quant = 0
    val ScaleQ16 = 1
    val InvQacQ16 = 2
    val InvDcFactorQ16Base = 3
    val XQmMultiplierQ16 = 6
    val Ytox = 7
    val Ytob = 8
  }
}
