#!/usr/bin/env python3
"""Generate checked Scala and Python constants from abi/hjxl_abi.json."""

from __future__ import annotations

import argparse
import json
from pathlib import Path
import sys


REPO_ROOT = Path(__file__).resolve().parents[1]
SCHEMA_PATH = REPO_ROOT / "abi" / "hjxl_abi.json"
SCALA_PATH = REPO_ROOT / "src" / "main" / "scala" / "hjxl" / "HjxlAbiGenerated.scala"
PYTHON_PATH = REPO_ROOT / "tools" / "hjxl_abi_generated.py"


def _load_schema() -> dict[str, object]:
    schema = json.loads(SCHEMA_PATH.read_text())
    if schema.get("schema_version") != 1:
        raise ValueError("abi schema_version must be 1")

    axi = schema["axi_lite"]
    if axi["data_bits"] % 8:
        raise ValueError("axi_lite.data_bits must be byte-aligned")
    register_offsets = [row["offset"] for row in axi["registers"]]
    if len(register_offsets) != len(set(register_offsets)):
        raise ValueError("AXI-Lite register offsets must be unique")
    if any(offset % (axi["data_bits"] // 8) for offset in register_offsets):
        raise ValueError("AXI-Lite register offsets must be word-aligned")

    trace = schema["trace"]
    field_names = [row["name"] for row in trace["fields"]]
    if field_names != ["stage", "group", "index", "value"]:
        raise ValueError("trace fields must remain ordered stage, group, index, value")
    stage_values = [row["value"] for row in trace["stages"]]
    if len(stage_values) != len(set(stage_values)):
        raise ValueError("trace stage values must be unique")

    prepared = schema["prepared_dct_stream"]
    scalar_offsets = [row["offset"] for row in prepared["scalar_fields"]]
    if max(scalar_offsets) >= prepared["scalar_words"]:
        raise ValueError("prepared scalar field offset exceeds scalar_words")
    return schema


def _render_scala(schema: dict[str, object]) -> str:
    axi = schema["axi_lite"]
    trace = schema["trace"]
    prepared = schema["prepared_dct_stream"]
    lines = [
        "// Generated by tools/hjxl_generate_abi.py. Do not edit by hand.",
        "",
        "package hjxl",
        "",
        "object HjxlAbiGenerated {",
        f"  val SchemaVersion = {schema['schema_version']}",
        "",
        "  object AxiLite {",
        f"    val AddrBits = {axi['addr_bits']}",
        f"    val DataBits = {axi['data_bits']}",
        f"    val StrbBits = {axi['data_bits'] // 8}",
        "",
        "    object Register {",
    ]
    lines.extend(f"      val {row['scala_name']} = {row['offset']}" for row in axi["registers"])
    lines.extend(["    }", "", "    object StatusBit {"])
    lines.extend(f"      val {row['scala_name']} = {row['bit']}" for row in axi["status_bits"])
    lines.extend(["    }", "", "    object ControlBit {"])
    lines.extend(f"      val {row['scala_name']} = {row['bit']}" for row in axi["control_bits"])
    lines.extend(["    }", "  }", "", "  object Trace {"])
    shift = 0
    for row in trace["fields"]:
        lines.extend(
            [
                f"    val {row['scala_name']}Bits = {row['bits']}",
                f"    val {row['scala_name']}Shift = {shift}",
            ]
        )
        shift += row["bits"]
    lines.extend(
        [
            f"    val PackedBits = {shift}",
            f"    val PackedBytes = {(shift + 7) // 8}",
            f"    val Kv260CaptureWordBytes = {trace['kv260_capture_word_bytes']}",
            "",
            "    object Stage {",
        ]
    )
    lines.extend(f"      val {row['scala_name']} = {row['value']}" for row in trace["stages"])
    lines.extend(["    }", "  }", "", "  object TokenSelect {"])
    lines.extend(f"    val {row['scala_name']} = {row['value']}" for row in schema["token_select"])
    coefficient_words = prepared["channels"] * prepared["coefficients_per_channel"]
    lines.extend(
        [
            "  }",
            "",
            "  object PreparedDctStream {",
            f"    val WordBits = {prepared['word_bits']}",
            f"    val ScalarWords = {prepared['scalar_words']}",
            f"    val Channels = {prepared['channels']}",
            f"    val CoefficientsPerChannel = {prepared['coefficients_per_channel']}",
            f"    val CoefficientWords = {coefficient_words}",
            f"    val WordsPerBlock = {prepared['scalar_words'] + coefficient_words}",
            f"    val CoefficientBase = {prepared['scalar_words']}",
        ]
    )
    lines.extend(f"    val {row['scala_name']} = {row['offset']}" for row in prepared["scalar_fields"])
    lines.extend(["  }", "}", ""])
    return "\n".join(lines)


def _render_python(schema: dict[str, object]) -> str:
    axi = schema["axi_lite"]
    trace = schema["trace"]
    prepared = schema["prepared_dct_stream"]
    fields = {row["name"]: row for row in trace["fields"]}
    shifts: dict[str, int] = {}
    shift = 0
    for row in trace["fields"]:
        shifts[row["name"]] = shift
        shift += row["bits"]
    lines = [
        '# Generated by tools/hjxl_generate_abi.py. Do not edit by hand.',
        "",
        f"ABI_SCHEMA_VERSION = {schema['schema_version']}",
        f"AXI_LITE_ADDR_BITS = {axi['addr_bits']}",
        f"AXI_LITE_DATA_BITS = {axi['data_bits']}",
        f"AXI_LITE_STRB_BITS = {axi['data_bits'] // 8}",
        "REGISTER_MAP = {",
    ]
    lines.extend(f'    "{row["name"]}": {row["offset"]},' for row in axi["registers"])
    lines.append("}")
    lines.extend(f"REGISTER_{row['name'].upper()} = {row['offset']}" for row in axi["registers"])
    lines.append("STATUS_BITS = {")
    lines.extend(f'    "{row["name"]}": {row["bit"]},' for row in axi["status_bits"])
    lines.append("}")
    lines.extend(f"STATUS_{row['name'].upper()} = {row['bit']}" for row in axi["status_bits"])
    lines.append("CONTROL_BITS = {")
    lines.extend(f'    "{row["name"]}": {row["bit"]},' for row in axi["control_bits"])
    lines.append("}")
    lines.extend(f"CONTROL_{row['name'].upper()} = {row['bit']}" for row in axi["control_bits"])
    lines.append("")
    for name in ("stage", "group", "index", "value"):
        lines.extend(
            [
                f"TRACE_{name.upper()}_BITS = {fields[name]['bits']}",
                f"TRACE_{name.upper()}_SHIFT = {shifts[name]}",
                f"TRACE_{name.upper()}_MASK = {(1 << fields[name]['bits']) - 1}",
                f"TRACE_{name.upper()}_BYTE_OFFSET = {shifts[name] // 8}",
            ]
        )
    packed_bytes = (shift + 7) // 8
    lines.extend(
        [
            f"TRACE_PACKED_BITS = {shift}",
            f"TRACE_PACKED_BYTES = {packed_bytes}",
            f"TRACE_TKEEP_MASK = {(1 << packed_bytes) - 1}",
            f"KV260_TRACE_CAPTURE_WORD_BYTES = {trace['kv260_capture_word_bytes']}",
            "TRACE_STAGES = {",
        ]
    )
    lines.extend(f'    "{row["name"]}": {row["value"]},' for row in trace["stages"])
    lines.append("}")
    lines.append("TRACE_STAGES_BY_SCALA_NAME = {")
    lines.extend(f'    "{row["scala_name"]}": {row["value"]},' for row in trace["stages"])
    lines.append("}")
    lines.extend(
        f"TRACE_STAGE_{row['scala_name'].upper()} = {row['value']}" for row in trace["stages"]
    )
    lines.extend(["TOKEN_SELECT = {"])
    lines.extend(f'    "{row["name"]}": {row["value"]},' for row in schema["token_select"])
    lines.append("}")
    coefficient_words = prepared["channels"] * prepared["coefficients_per_channel"]
    lines.extend(
        [
            f"PREPARED_DCT_WORD_BITS = {prepared['word_bits']}",
            f"PREPARED_DCT_SCALAR_WORDS = {prepared['scalar_words']}",
            f"PREPARED_DCT_CHANNELS = {prepared['channels']}",
            f"PREPARED_DCT_COEFFICIENTS_PER_CHANNEL = {prepared['coefficients_per_channel']}",
            f"PREPARED_DCT_COEFFICIENT_WORDS = {coefficient_words}",
            f"PREPARED_DCT_WORDS_PER_BLOCK = {prepared['scalar_words'] + coefficient_words}",
            f"PREPARED_DCT_COEFFICIENT_BASE = {prepared['scalar_words']}",
            "PREPARED_DCT_SCALAR_FIELDS = {",
        ]
    )
    lines.extend(f'    "{row["name"]}": {row["offset"]},' for row in prepared["scalar_fields"])
    lines.extend(["}", ""])
    return "\n".join(lines)


def _update(path: Path, content: str, *, check: bool) -> bool:
    current = path.read_text() if path.exists() else None
    if current == content:
        return True
    if check:
        print(f"stale generated ABI file: {path.relative_to(REPO_ROOT)}", file=sys.stderr)
        return False
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content)
    print(f"wrote {path.relative_to(REPO_ROOT)}")
    return True


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="fail if generated files differ from the schema")
    args = parser.parse_args()
    schema = _load_schema()
    okay = all(
        (
            _update(SCALA_PATH, _render_scala(schema), check=args.check),
            _update(PYTHON_PATH, _render_python(schema), check=args.check),
        )
    )
    if args.check and okay:
        print("generated ABI files are current")
    return 0 if okay else 1


if __name__ == "__main__":
    raise SystemExit(main())
