#!/usr/bin/env python3
"""Generate a small C header from an HJXL stream/control manifest."""

from __future__ import annotations

import argparse
import json
from pathlib import Path
import re


SUPPORTED_FORMATS = {
    "hjxl.rgb_stream_manifest.v1": "RGB stream input",
    "hjxl.prepared_dct_stream_manifest.v1": "prepared DCT stream input",
}

CONFIG_REGISTER_KEYS = (
    ("xsize", "xsize"),
    ("ysize", "ysize"),
    ("distance_q8", "distance_q8"),
    ("fixed_point_scale", "fixed_point_scale"),
    ("fixed_inv_qac_q16", "fixed_inv_qac_q16"),
    ("fixed_raw_quant", "fixed_raw_quant"),
    ("flags", "flags"),
)


def _symbol(value: str) -> str:
    symbol = re.sub(r"[^A-Za-z0-9_]", "_", value).upper()
    symbol = re.sub(r"_+", "_", symbol).strip("_")
    if not symbol:
        raise ValueError("symbol prefix must contain at least one letter or digit")
    if symbol[0].isdigit():
        symbol = f"_{symbol}"
    return symbol


def _u32(value: object) -> int:
    parsed = int(value)
    if parsed < 0 or parsed > 0xFFFFFFFF:
        raise ValueError(f"{value!r} does not fit in uint32_t")
    return parsed


def _hex(value: int) -> str:
    return f"0x{value:08x}u"


def register_writes(manifest: dict) -> list[tuple[str, int, int, int]]:
    axi_lite = manifest["axi_lite"]
    register_map = axi_lite["register_map"]
    config = axi_lite["config"]
    rows = []
    for register_key, config_key in CONFIG_REGISTER_KEYS:
        rows.append(
            (
                register_key,
                _u32(register_map[register_key]),
                _u32(config[config_key]),
                0xF,
            )
        )
    return rows


def input_data_bits(manifest: dict) -> int:
    stream = manifest["stream"]
    if "pixel_bits" in stream:
        return int(stream["pixel_bits"]) * 3
    return 32


def input_data_bytes(manifest: dict) -> int:
    return (input_data_bits(manifest) + 7) // 8


def header_text(manifest: dict, *, symbol_prefix: str, include_guard: str | None) -> str:
    manifest_format = str(manifest.get("format", ""))
    if manifest_format not in SUPPORTED_FORMATS:
        raise ValueError(f"unsupported manifest format {manifest_format!r}")

    prefix = _symbol(symbol_prefix)
    guard = _symbol(include_guard or f"{prefix}_H")
    stream = manifest["stream"]
    axi_lite = manifest["axi_lite"]
    status_bits = axi_lite["status_control_bits"]
    register_map = axi_lite["register_map"]
    rows = register_writes(manifest)
    word_count = _u32(stream["word_count"])
    stream_data_bits = input_data_bits(manifest)
    stream_data_bytes = input_data_bytes(manifest)

    lines = [
        "/* Generated by tools/hjxl_manifest_header.py; do not edit by hand. */",
        f"#ifndef {guard}",
        f"#define {guard}",
        "",
        "#include <stdint.h>",
        "",
        "typedef struct {",
        "  uint32_t address;",
        "  uint32_t data;",
        "  uint32_t strb;",
        f"}} {prefix.lower()}_axi_lite_write_t;",
        "",
        f"#define {prefix}_MANIFEST_FORMAT \"{manifest_format}\"",
        f"#define {prefix}_MANIFEST_DESCRIPTION \"{SUPPORTED_FORMATS[manifest_format]}\"",
        f"#define {prefix}_STREAM_WORD_COUNT {word_count}u",
        f"#define {prefix}_INPUT_DATA_BITS {stream_data_bits}u",
        f"#define {prefix}_STREAM_WORD_BYTES {stream_data_bytes}u",
        f"#define {prefix}_STREAM_BYTE_COUNT {word_count * stream_data_bytes}u",
        f"#define {prefix}_AXI_LITE_WRITE_COUNT {len(rows)}u",
        "",
    ]

    for name, address in sorted(register_map.items(), key=lambda item: int(item[1])):
        lines.append(f"#define {prefix}_REG_{_symbol(name)} {_hex(_u32(address))}")
    lines.extend(
        [
            "",
            f"#define {prefix}_STATUS_PROTOCOL_ERROR_BIT {_u32(status_bits['protocol_error'])}u",
            f"#define {prefix}_STATUS_BUSY_BIT {_u32(status_bits['busy'])}u",
            f"#define {prefix}_STATUS_OVERFLOW_BIT {_u32(status_bits['overflow'])}u",
            "#define "
            f"{prefix}_CONTROL_CLEAR_PROTOCOL_ERROR_BIT "
            f"{_u32(status_bits['clear_protocol_error_write_bit'])}u",
            "",
            f"static const {prefix.lower()}_axi_lite_write_t {prefix}_AXI_LITE_WRITES[] = {{",
        ]
    )
    for register_key, address, data, strb in rows:
        lines.append(
            f"  {{ {_hex(address)}, {_hex(data)}, {_hex(strb)} }},"
            f" /* {register_key} */"
        )
    lines.extend(
        [
            "};",
            "",
            "#if defined(__cplusplus)",
            "static_assert("
            f"{prefix}_STREAM_BYTE_COUNT == {prefix}_STREAM_WORD_COUNT * {prefix}_STREAM_WORD_BYTES, "
            '"stream byte count mismatch");',
            "static_assert("
            f"sizeof({prefix}_AXI_LITE_WRITES) / sizeof({prefix}_AXI_LITE_WRITES[0]) == "
            f"{prefix}_AXI_LITE_WRITE_COUNT, "
            '"AXI-Lite write count mismatch");',
            "#elif defined(__STDC_VERSION__) && __STDC_VERSION__ >= 201112L",
            "_Static_assert("
            f"{prefix}_STREAM_BYTE_COUNT == {prefix}_STREAM_WORD_COUNT * {prefix}_STREAM_WORD_BYTES, "
            '"stream byte count mismatch");',
            "_Static_assert("
            f"sizeof({prefix}_AXI_LITE_WRITES) / sizeof({prefix}_AXI_LITE_WRITES[0]) == "
            f"{prefix}_AXI_LITE_WRITE_COUNT, "
            '"AXI-Lite write count mismatch");',
            "#endif",
            "",
            f"#endif /* {guard} */",
            "",
        ]
    )
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--manifest-json", type=Path, required=True, help="HJXL stream/control manifest")
    parser.add_argument("--header", type=Path, required=True, help="output C header path")
    parser.add_argument(
        "--symbol-prefix",
        default="HJXL_BUNDLE",
        help="C symbol prefix for generated macros and objects",
    )
    parser.add_argument("--include-guard", help="explicit C include guard")
    args = parser.parse_args()

    try:
        with args.manifest_json.open("r", encoding="utf-8") as handle:
            manifest = json.load(handle)
        text = header_text(
            manifest,
            symbol_prefix=args.symbol_prefix,
            include_guard=args.include_guard,
        )
        args.header.parent.mkdir(parents=True, exist_ok=True)
        args.header.write_text(text, encoding="utf-8")
    except (OSError, KeyError, TypeError, ValueError) as exc:
        raise SystemExit(f"error: {exc}") from exc

    print(f"wrote {args.header}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
