# Generated by tools/hjxl_generate_abi.py. Do not edit by hand.

ABI_SCHEMA_VERSION = 1
AXI_LITE_ADDR_BITS = 8
AXI_LITE_DATA_BITS = 32
AXI_LITE_STRB_BITS = 4
REGISTER_MAP = {
    "status_control": 0,
    "xsize": 4,
    "ysize": 8,
    "distance_q8": 12,
    "fixed_point_scale": 16,
    "fixed_inv_qac_q16": 20,
    "fixed_raw_quant": 24,
    "flags": 28,
    "fixed_ytox": 32,
    "fixed_ytob": 36,
    "identity": 40,
    "abi_version": 44,
    "capabilities": 48,
    "max_frame_geometry": 52,
    "active_route": 56,
    "build_id": 60,
}
REGISTER_STATUS_CONTROL = 0
REGISTER_XSIZE = 4
REGISTER_YSIZE = 8
REGISTER_DISTANCE_Q8 = 12
REGISTER_FIXED_POINT_SCALE = 16
REGISTER_FIXED_INV_QAC_Q16 = 20
REGISTER_FIXED_RAW_QUANT = 24
REGISTER_FLAGS = 28
REGISTER_FIXED_YTOX = 32
REGISTER_FIXED_YTOB = 36
REGISTER_IDENTITY = 40
REGISTER_ABI_VERSION = 44
REGISTER_CAPABILITIES = 48
REGISTER_MAX_FRAME_GEOMETRY = 52
REGISTER_ACTIVE_ROUTE = 56
REGISTER_BUILD_ID = 60
REGISTER_ACCESS = {
    "status_control": "rw1c",
    "xsize": "rw",
    "ysize": "rw",
    "distance_q8": "rw",
    "fixed_point_scale": "rw",
    "fixed_inv_qac_q16": "rw",
    "fixed_raw_quant": "rw",
    "flags": "rw",
    "fixed_ytox": "rw",
    "fixed_ytob": "rw",
    "identity": "ro",
    "abi_version": "ro",
    "capabilities": "ro",
    "max_frame_geometry": "ro",
    "active_route": "ro",
    "build_id": "ro",
}
STATUS_BITS = {
    "protocol_error": 0,
    "busy": 1,
    "overflow": 2,
    "unsupported_distance": 3,
}
STATUS_PROTOCOL_ERROR = 0
STATUS_BUSY = 1
STATUS_OVERFLOW = 2
STATUS_UNSUPPORTED_DISTANCE = 3
CONTROL_BITS = {
    "clear_protocol_error": 0,
}
CONTROL_CLEAR_PROTOCOL_ERROR = 0

TRACE_STAGE_BITS = 8
TRACE_STAGE_SHIFT = 0
TRACE_STAGE_MASK = 255
TRACE_STAGE_BYTE_OFFSET = 0
TRACE_GROUP_BITS = 16
TRACE_GROUP_SHIFT = 8
TRACE_GROUP_MASK = 65535
TRACE_GROUP_BYTE_OFFSET = 1
TRACE_INDEX_BITS = 32
TRACE_INDEX_SHIFT = 24
TRACE_INDEX_MASK = 4294967295
TRACE_INDEX_BYTE_OFFSET = 3
TRACE_VALUE_BITS = 32
TRACE_VALUE_SHIFT = 56
TRACE_VALUE_MASK = 4294967295
TRACE_VALUE_BYTE_OFFSET = 7
TRACE_PACKED_BITS = 88
TRACE_PACKED_BYTES = 11
TRACE_TKEEP_MASK = 2047
KV260_TRACE_CAPTURE_WORD_BYTES = 16
TRACE_STAGES = {
    "input-padded": 0,
    "xyb": 1,
    "raw-dct8x8": 2,
    "raw-quant-field": 3,
    "ytox-map": 4,
    "ytob-map": 5,
    "ac-strategy": 6,
    "quant-dc": 7,
    "quantized-ac": 8,
    "num-nonzeros": 9,
    "dc-tokens": 10,
    "ac-metadata-tokens": 11,
    "ac-tokens": 12,
    "aq-contrast": 13,
    "aq-fuzzy-erosion": 14,
    "aq-strategy-mask": 15,
    "aq-nonlinear-mask": 16,
    "aq-hf-modulation": 17,
    "aq-color-modulation": 18,
}
TRACE_STAGES_BY_SCALA_NAME = {
    "InputPadded": 0,
    "Xyb": 1,
    "RawDct8x8": 2,
    "RawQuantField": 3,
    "YtoxMap": 4,
    "YtobMap": 5,
    "AcStrategy": 6,
    "QuantDc": 7,
    "QuantizedAc": 8,
    "NumNonzeros": 9,
    "DcTokens": 10,
    "AcMetadataTokens": 11,
    "AcTokens": 12,
    "AqContrast": 13,
    "AqFuzzyErosion": 14,
    "AqStrategyMask": 15,
    "AqNonlinearMask": 16,
    "AqHfModulation": 17,
    "AqColorModulation": 18,
}
TRACE_STAGE_INPUTPADDED = 0
TRACE_STAGE_XYB = 1
TRACE_STAGE_RAWDCT8X8 = 2
TRACE_STAGE_RAWQUANTFIELD = 3
TRACE_STAGE_YTOXMAP = 4
TRACE_STAGE_YTOBMAP = 5
TRACE_STAGE_ACSTRATEGY = 6
TRACE_STAGE_QUANTDC = 7
TRACE_STAGE_QUANTIZEDAC = 8
TRACE_STAGE_NUMNONZEROS = 9
TRACE_STAGE_DCTOKENS = 10
TRACE_STAGE_ACMETADATATOKENS = 11
TRACE_STAGE_ACTOKENS = 12
TRACE_STAGE_AQCONTRAST = 13
TRACE_STAGE_AQFUZZYEROSION = 14
TRACE_STAGE_AQSTRATEGYMASK = 15
TRACE_STAGE_AQNONLINEARMASK = 16
TRACE_STAGE_AQHFMODULATION = 17
TRACE_STAGE_AQCOLORMODULATION = 18
TOKEN_SELECT = {
    "dc": 0,
    "ac-metadata": 1,
    "ac-tokens": 2,
    "aq-contrast": 3,
}
DISCOVERY_IDENTITY = 1212831820
DISCOVERY_ABI_MAJOR = 1
DISCOVERY_ABI_MINOR = 6
DISCOVERY_ABI_VERSION = 65542
DISCOVERY_BUILD_ID = 539363090
CAPABILITY_BITS = {
    "rgb_input": 0,
    "prepared_dct_input": 1,
    "estimated_cfl": 2,
    "axi_lite": 3,
    "axi_stream": 4,
    "trace_output": 5,
    "host_bitstream_assembly_required": 6,
    "frame_config_snapshot": 7,
    "full_word_input_keep": 8,
    "caller_cfl": 9,
}
CAPABILITY_RGB_INPUT = 0
CAPABILITY_PREPARED_DCT_INPUT = 1
CAPABILITY_ESTIMATED_CFL = 2
CAPABILITY_AXI_LITE = 3
CAPABILITY_AXI_STREAM = 4
CAPABILITY_TRACE_OUTPUT = 5
CAPABILITY_HOST_BITSTREAM_ASSEMBLY_REQUIRED = 6
CAPABILITY_FRAME_CONFIG_SNAPSHOT = 7
CAPABILITY_FULL_WORD_INPUT_KEEP = 8
CAPABILITY_CALLER_CFL = 9
CAPABILITY_PROFILES = {
    "rgb": 249,
    "prepared-direct": 1018,
    "prepared-estimated-cfl": 510,
}
ROUTE_IDS = {
    "prepared-direct": 128,
    "prepared-estimated-cfl": 129,
    "unavailable": 255,
}
PREPARED_DCT_WORD_BITS = 32
PREPARED_DCT_SCALAR_WORDS = 9
PREPARED_DCT_CHANNELS = 3
PREPARED_DCT_COEFFICIENTS_PER_CHANNEL = 64
PREPARED_DCT_COEFFICIENT_WORDS = 192
PREPARED_DCT_WORDS_PER_BLOCK = 201
PREPARED_DCT_COEFFICIENT_BASE = 9
PREPARED_DCT_SCALAR_FIELDS = {
    "quant": 0,
    "scale_q16": 1,
    "inv_qac_q16": 2,
    "inv_dc_factor_q16_base": 3,
    "x_qm_multiplier_q16": 6,
    "ytox": 7,
    "ytob": 8,
}
