#!/usr/bin/env python3
"""Generate a small C header from an HJXL stream/control manifest."""

from __future__ import annotations

import argparse
import copy
import json
from pathlib import Path
import re


SUPPORTED_FORMATS = {
    "hjxl.rgb_stream_manifest.v1": "RGB stream input",
    "hjxl.prepared_dct_stream_manifest.v1": "prepared DCT stream input",
}

TARGETS = {
    "hjxl.rgb_stream_manifest.v1": {
        "interface": "rgb_axi_stream",
        "stream_shell": "HjxlAxiStreamCore",
        "controlled_shell": "HjxlAxiLiteStreamCore",
        "kv260_top": None,
        "input_stream": "raster RGB pixels",
    },
    "hjxl.prepared_dct_stream_manifest.v1": {
        "interface": "prepared_dct_axi_stream",
        "stream_shell": "HjxlPreparedDctAxiStreamCore",
        "controlled_shell": "HjxlPreparedDctAxiLiteStreamCore",
        "kv260_top": "HjxlKv260PreparedDctTop",
        "input_stream": "prepared DCT-only block words",
    },
}

TRACE_STAGE_BITS = 8
TRACE_GROUP_BITS = 16
TRACE_INDEX_BITS = 32
TRACE_VALUE_BITS = 32
TRACE_PACKED_BITS = TRACE_STAGE_BITS + TRACE_GROUP_BITS + TRACE_INDEX_BITS + TRACE_VALUE_BITS
TRACE_PACKED_BYTES = (TRACE_PACKED_BITS + 7) // 8
KV260_TRACE_CAPTURE_WORD_BYTES = 16
DEFAULT_DISTANCE_Q8 = 256
SUPPORTED_DISTANCE_Q8 = (64, 128, 256, 512, 1024, 2048)

CONFIG_REGISTER_KEYS = (
    ("xsize", "xsize"),
    ("ysize", "ysize"),
    ("distance_q8", "distance_q8"),
    ("fixed_point_scale", "fixed_point_scale"),
    ("fixed_inv_qac_q16", "fixed_inv_qac_q16"),
    ("fixed_raw_quant", "fixed_raw_quant"),
    ("flags", "flags"),
)


def _symbol(value: str) -> str:
    symbol = re.sub(r"[^A-Za-z0-9_]", "_", value).upper()
    symbol = re.sub(r"_+", "_", symbol).strip("_")
    if not symbol:
        raise ValueError("symbol prefix must contain at least one letter or digit")
    if symbol[0].isdigit():
        symbol = f"_{symbol}"
    return symbol


def _u32(value: object) -> int:
    parsed = int(value)
    if parsed < 0 or parsed > 0xFFFFFFFF:
        raise ValueError(f"{value!r} does not fit in uint32_t")
    return parsed


def _hex(value: int) -> str:
    return f"0x{value:08x}u"


def _c_string(value: object) -> str:
    if value is None:
        return ""
    return value.replace("\\", "\\\\").replace("\"", "\\\"")


def _status_bit(status_bits: dict, key: str, default: int | None = None) -> int:
    if key in status_bits:
        return _u32(status_bits[key])
    if default is not None:
        return _u32(default)
    raise KeyError(key)


def target_metadata(manifest_format: str | None) -> dict:
    if manifest_format not in TARGETS:
        raise ValueError(f"unsupported manifest format {manifest_format!r}")
    return copy.deepcopy(TARGETS[manifest_format])


def distance_metadata() -> dict:
    return {
        "fallback_q8": DEFAULT_DISTANCE_Q8,
        "supported_q8": list(SUPPORTED_DISTANCE_Q8),
    }


def register_writes(manifest: dict) -> list[tuple[str, int, int, int]]:
    axi_lite = manifest["axi_lite"]
    register_map = axi_lite["register_map"]
    config = axi_lite["config"]
    rows = []
    for register_key, config_key in CONFIG_REGISTER_KEYS:
        rows.append(
            (
                register_key,
                _u32(register_map[register_key]),
                _u32(config[config_key]),
                0xF,
            )
        )
    return rows


def input_data_bits(manifest: dict) -> int:
    stream = manifest["stream"]
    if "pixel_bits" in stream:
        return int(stream["pixel_bits"]) * 3
    return 32


def input_data_bytes(manifest: dict) -> int:
    return (input_data_bits(manifest) + 7) // 8


def header_text(manifest: dict, *, symbol_prefix: str, include_guard: str | None) -> str:
    manifest_format = str(manifest.get("format", ""))
    if manifest_format not in SUPPORTED_FORMATS:
        raise ValueError(f"unsupported manifest format {manifest_format!r}")

    prefix = _symbol(symbol_prefix)
    guard = _symbol(include_guard or f"{prefix}_H")
    stream = manifest["stream"]
    axi_lite = manifest["axi_lite"]
    status_bits = axi_lite["status_control_bits"]
    register_map = axi_lite["register_map"]
    rows = register_writes(manifest)
    word_count = _u32(stream["word_count"])
    stream_data_bits = input_data_bits(manifest)
    stream_data_bytes = input_data_bytes(manifest)
    target = target_metadata(manifest_format)

    lines = [
        "/* Generated by tools/hjxl_manifest_header.py; do not edit by hand. */",
        f"#ifndef {guard}",
        f"#define {guard}",
        "",
        "#include <stdint.h>",
        "",
        "typedef struct {",
        "  uint32_t address;",
        "  uint32_t data;",
        "  uint32_t strb;",
        f"}} {prefix.lower()}_axi_lite_write_t;",
        "",
        f"#define {prefix}_MANIFEST_FORMAT \"{manifest_format}\"",
        f"#define {prefix}_MANIFEST_DESCRIPTION \"{SUPPORTED_FORMATS[manifest_format]}\"",
        f"#define {prefix}_TARGET_INTERFACE \"{_c_string(target['interface'])}\"",
        f"#define {prefix}_TARGET_STREAM_SHELL \"{_c_string(target['stream_shell'])}\"",
        f"#define {prefix}_TARGET_CONTROLLED_SHELL \"{_c_string(target['controlled_shell'])}\"",
        f"#define {prefix}_TARGET_KV260_TOP \"{_c_string(target['kv260_top'])}\"",
        f"#define {prefix}_TARGET_INPUT_STREAM \"{_c_string(target['input_stream'])}\"",
        f"#define {prefix}_STREAM_WORD_COUNT {word_count}u",
        f"#define {prefix}_INPUT_DATA_BITS {stream_data_bits}u",
        f"#define {prefix}_STREAM_WORD_BYTES {stream_data_bytes}u",
        f"#define {prefix}_STREAM_BYTE_COUNT {word_count * stream_data_bytes}u",
        f"#define {prefix}_AXI_LITE_WRITE_COUNT {len(rows)}u",
        f"#define {prefix}_TRACE_STAGE_BITS {TRACE_STAGE_BITS}u",
        f"#define {prefix}_TRACE_GROUP_BITS {TRACE_GROUP_BITS}u",
        f"#define {prefix}_TRACE_INDEX_BITS {TRACE_INDEX_BITS}u",
        f"#define {prefix}_TRACE_VALUE_BITS {TRACE_VALUE_BITS}u",
        f"#define {prefix}_TRACE_PACKED_BITS {TRACE_PACKED_BITS}u",
        f"#define {prefix}_TRACE_PACKED_BYTES {TRACE_PACKED_BYTES}u",
        f"#define {prefix}_KV260_TRACE_CAPTURE_WORD_BYTES {KV260_TRACE_CAPTURE_WORD_BYTES}u",
        f"#define {prefix}_DISTANCE_FALLBACK_Q8 {DEFAULT_DISTANCE_Q8}u",
        f"#define {prefix}_SUPPORTED_DISTANCE_Q8_COUNT {len(SUPPORTED_DISTANCE_Q8)}u",
        "",
    ]

    for name, address in sorted(register_map.items(), key=lambda item: int(item[1])):
        lines.append(f"#define {prefix}_REG_{_symbol(name)} {_hex(_u32(address))}")
    lines.extend(
        [
            "",
            f"#define {prefix}_STATUS_PROTOCOL_ERROR_BIT {_u32(status_bits['protocol_error'])}u",
            f"#define {prefix}_STATUS_BUSY_BIT {_u32(status_bits['busy'])}u",
            f"#define {prefix}_STATUS_OVERFLOW_BIT {_u32(status_bits['overflow'])}u",
            f"#define {prefix}_STATUS_UNSUPPORTED_DISTANCE_BIT {_status_bit(status_bits, 'unsupported_distance', 3)}u",
            "#define "
            f"{prefix}_CONTROL_CLEAR_PROTOCOL_ERROR_BIT "
            f"{_u32(status_bits['clear_protocol_error_write_bit'])}u",
            "",
            f"static const uint32_t {prefix}_SUPPORTED_DISTANCE_Q8[] = {{",
            "  " + ", ".join(f"{value}u" for value in SUPPORTED_DISTANCE_Q8),
            "};",
            "",
            f"static const {prefix.lower()}_axi_lite_write_t {prefix}_AXI_LITE_WRITES[] = {{",
        ]
    )
    for register_key, address, data, strb in rows:
        lines.append(
            f"  {{ {_hex(address)}, {_hex(data)}, {_hex(strb)} }},"
            f" /* {register_key} */"
        )
    lines.extend(
        [
            "};",
            "",
            "#if defined(__cplusplus)",
            "static_assert("
            f"{prefix}_STREAM_BYTE_COUNT == {prefix}_STREAM_WORD_COUNT * {prefix}_STREAM_WORD_BYTES, "
            '"stream byte count mismatch");',
            "static_assert("
            f"sizeof({prefix}_AXI_LITE_WRITES) / sizeof({prefix}_AXI_LITE_WRITES[0]) == "
            f"{prefix}_AXI_LITE_WRITE_COUNT, "
            '"AXI-Lite write count mismatch");',
            "static_assert("
            f"{prefix}_TRACE_PACKED_BYTES == ({prefix}_TRACE_PACKED_BITS + 7u) / 8u, "
            '"trace packed byte count mismatch");',
            "static_assert("
            f"sizeof({prefix}_SUPPORTED_DISTANCE_Q8) / sizeof({prefix}_SUPPORTED_DISTANCE_Q8[0]) == "
            f"{prefix}_SUPPORTED_DISTANCE_Q8_COUNT, "
            '"supported distance count mismatch");',
            "#elif defined(__STDC_VERSION__) && __STDC_VERSION__ >= 201112L",
            "_Static_assert("
            f"{prefix}_STREAM_BYTE_COUNT == {prefix}_STREAM_WORD_COUNT * {prefix}_STREAM_WORD_BYTES, "
            '"stream byte count mismatch");',
            "_Static_assert("
            f"sizeof({prefix}_AXI_LITE_WRITES) / sizeof({prefix}_AXI_LITE_WRITES[0]) == "
            f"{prefix}_AXI_LITE_WRITE_COUNT, "
            '"AXI-Lite write count mismatch");',
            "_Static_assert("
            f"{prefix}_TRACE_PACKED_BYTES == ({prefix}_TRACE_PACKED_BITS + 7u) / 8u, "
            '"trace packed byte count mismatch");',
            "_Static_assert("
            f"sizeof({prefix}_SUPPORTED_DISTANCE_Q8) / sizeof({prefix}_SUPPORTED_DISTANCE_Q8[0]) == "
            f"{prefix}_SUPPORTED_DISTANCE_Q8_COUNT, "
            '"supported distance count mismatch");',
            "#endif",
            "",
            f"#endif /* {guard} */",
            "",
        ]
    )
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--manifest-json", type=Path, required=True, help="HJXL stream/control manifest")
    parser.add_argument("--header", type=Path, required=True, help="output C header path")
    parser.add_argument(
        "--symbol-prefix",
        default="HJXL_BUNDLE",
        help="C symbol prefix for generated macros and objects",
    )
    parser.add_argument("--include-guard", help="explicit C include guard")
    args = parser.parse_args()

    try:
        with args.manifest_json.open("r", encoding="utf-8") as handle:
            manifest = json.load(handle)
        text = header_text(
            manifest,
            symbol_prefix=args.symbol_prefix,
            include_guard=args.include_guard,
        )
        args.header.parent.mkdir(parents=True, exist_ok=True)
        args.header.write_text(text, encoding="utf-8")
    except (OSError, KeyError, TypeError, ValueError) as exc:
        raise SystemExit(f"error: {exc}") from exc

    print(f"wrote {args.header}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
